# Generated by Django 5.0.14 on 2026-02-04 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GitHubStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_repos", models.PositiveIntegerField(default=0)),
                ("total_stars", models.PositiveIntegerField(default=0)),
                ("total_forks", models.PositiveIntegerField(default=0)),
                ("total_followers", models.PositiveIntegerField(default=0)),
                ("total_following", models.PositiveIntegerField(default=0)),
                ("public_repos", models.PositiveIntegerField(default=0)),
                ("public_gists", models.PositiveIntegerField(default=0)),
                (
                    "total_contributions_last_year",
                    models.PositiveIntegerField(default=0),
                ),
                ("contribution_streak", models.PositiveIntegerField(default=0)),
                ("top_languages", models.JSONField(default=dict)),
                ("profile_data", models.JSONField(default=dict)),
                ("last_synced_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "GitHub Stats",
                "verbose_name_plural": "GitHub Stats",
            },
        ),
        migrations.CreateModel(
            name="GitHubRepo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("repo_id", models.PositiveIntegerField(unique=True)),
                ("name", models.CharField(max_length=100)),
                ("full_name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("html_url", models.URLField()),
                ("homepage", models.URLField(blank=True)),
                ("language", models.CharField(blank=True, max_length=50)),
                ("topics", models.JSONField(default=list)),
                ("stars_count", models.PositiveIntegerField(default=0)),
                ("forks_count", models.PositiveIntegerField(default=0)),
                ("watchers_count", models.PositiveIntegerField(default=0)),
                ("open_issues_count", models.PositiveIntegerField(default=0)),
                ("is_fork", models.BooleanField(default=False)),
                ("is_private", models.BooleanField(default=False)),
                ("is_archived", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
                ("pushed_at", models.DateTimeField(blank=True, null=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("is_hidden", models.BooleanField(default=False)),
                ("last_synced_at", models.DateTimeField(auto_now=True)),
                (
                    "linked_project",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="github_repo_data",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "GitHub Repository",
                "verbose_name_plural": "GitHub Repositories",
                "ordering": ["-pushed_at", "-stars_count"],
            },
        ),
    ]
