# Generated by Django 5.0.14 on 2026-02-04 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("professional_title", models.CharField(max_length=100)),
                ("professional_title_en", models.CharField(blank=True, max_length=100)),
                ("professional_title_fr", models.CharField(blank=True, max_length=100)),
                ("location", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("photo", models.ImageField(blank=True, upload_to="profile/")),
                (
                    "photo_alt",
                    models.CharField(default="Profile Photo", max_length=100),
                ),
                ("bio_short", models.TextField(help_text="Short bio for hero section")),
                ("bio_short_en", models.TextField(blank=True)),
                ("bio_short_fr", models.TextField(blank=True)),
                ("bio_full", models.TextField(help_text="Full bio for about section")),
                ("bio_full_en", models.TextField(blank=True)),
                ("bio_full_fr", models.TextField(blank=True)),
                ("resume_pdf", models.FileField(blank=True, upload_to="documents/")),
                ("github_username", models.CharField(max_length=50)),
                ("linkedin_url", models.URLField(blank=True)),
                ("instagram_url", models.URLField(blank=True)),
                ("is_available_for_hire", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Profile",
                "verbose_name_plural": "Profile",
            },
        ),
        migrations.CreateModel(
            name="SocialLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("github", "GitHub"),
                            ("linkedin", "LinkedIn"),
                            ("instagram", "Instagram"),
                            ("twitter", "Twitter/X"),
                            ("email", "Email"),
                            ("whatsapp", "WhatsApp"),
                            ("telegram", "Telegram"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("url", models.URLField()),
                (
                    "icon_class",
                    models.CharField(
                        blank=True, help_text="Font Awesome class", max_length=50
                    ),
                ),
                ("display_name", models.CharField(max_length=100)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_links",
                        to="profile.profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Social Link",
                "verbose_name_plural": "Social Links",
                "ordering": ["order"],
            },
        ),
    ]
