# Generated by Django 5.0.14 on 2026-02-04 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SkillCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("name_en", models.CharField(blank=True, max_length=50)),
                ("name_fr", models.CharField(blank=True, max_length=50)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("hard", "Hard Skills"),
                            ("soft", "Soft Skills"),
                            ("tools", "Tools"),
                            ("certifications", "Certifications"),
                        ],
                        max_length=20,
                    ),
                ),
                ("icon_class", models.CharField(blank=True, max_length=50)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Skill Category",
                "verbose_name_plural": "Skill Categories",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("name_en", models.CharField(blank=True, max_length=100)),
                ("name_fr", models.CharField(blank=True, max_length=100)),
                ("description", models.TextField(blank=True)),
                ("description_en", models.TextField(blank=True)),
                ("description_fr", models.TextField(blank=True)),
                (
                    "proficiency",
                    models.PositiveIntegerField(
                        default=0, help_text="Proficiency level 0-100"
                    ),
                ),
                ("icon_class", models.CharField(blank=True, max_length=50)),
                (
                    "icon_svg",
                    models.TextField(blank=True, help_text="SVG code for tech logos"),
                ),
                (
                    "color",
                    models.CharField(blank=True, help_text="Hex color", max_length=7),
                ),
                (
                    "years_experience",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=3, null=True
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_featured", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to="skills.skillcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Skill",
                "verbose_name_plural": "Skills",
                "ordering": ["-is_featured", "order"],
            },
        ),
    ]
