# Generated by Django 5.0.14 on 2026-02-04 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("skills", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Certification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("name_en", models.CharField(blank=True, max_length=100)),
                ("name_fr", models.CharField(blank=True, max_length=100)),
                ("issuing_organization", models.CharField(max_length=100)),
                (
                    "organization_logo",
                    models.ImageField(blank=True, upload_to="organizations/"),
                ),
                ("issue_date", models.DateField()),
                ("expiration_date", models.DateField(blank=True, null=True)),
                ("credential_id", models.CharField(blank=True, max_length=100)),
                ("credential_url", models.URLField(blank=True)),
                (
                    "certificate_file",
                    models.FileField(blank=True, upload_to="certificates/"),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Certification",
                "verbose_name_plural": "Certifications",
                "ordering": ["-issue_date"],
            },
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("institution", models.CharField(max_length=100)),
                (
                    "institution_logo",
                    models.ImageField(blank=True, upload_to="institutions/"),
                ),
                ("institution_url", models.URLField(blank=True)),
                (
                    "degree_type",
                    models.CharField(
                        choices=[
                            ("technologist", "Technologist"),
                            ("bachelor", "Bachelor"),
                            ("master", "Master"),
                            ("doctorate", "Doctorate"),
                            ("course", "Course"),
                            ("bootcamp", "Bootcamp"),
                        ],
                        max_length=20,
                    ),
                ),
                ("degree_name", models.CharField(max_length=100)),
                ("degree_name_en", models.CharField(blank=True, max_length=100)),
                ("degree_name_fr", models.CharField(blank=True, max_length=100)),
                ("field_of_study", models.CharField(blank=True, max_length=100)),
                ("description", models.TextField(blank=True)),
                ("description_en", models.TextField(blank=True)),
                ("description_fr", models.TextField(blank=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_current", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "skills_learned",
                    models.ManyToManyField(
                        blank=True, related_name="educations", to="skills.skill"
                    ),
                ),
            ],
            options={
                "verbose_name": "Education",
                "verbose_name_plural": "Education",
                "ordering": ["-is_current", "-start_date"],
            },
        ),
    ]
