# Generated by Django 5.0.14 on 2026-02-04 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("skills", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("title", models.CharField(max_length=100)),
                ("title_en", models.CharField(blank=True, max_length=100)),
                ("title_fr", models.CharField(blank=True, max_length=100)),
                ("short_description", models.CharField(max_length=200)),
                ("short_description_en", models.CharField(blank=True, max_length=200)),
                ("short_description_fr", models.CharField(blank=True, max_length=200)),
                ("full_description", models.TextField()),
                ("full_description_en", models.TextField(blank=True)),
                ("full_description_fr", models.TextField(blank=True)),
                (
                    "thumbnail",
                    models.ImageField(blank=True, upload_to="projects/thumbnails/"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("development", "In Development"),
                            ("completed", "Completed"),
                            ("archived", "Archived"),
                        ],
                        default="completed",
                        max_length=20,
                    ),
                ),
                (
                    "project_type",
                    models.CharField(
                        choices=[
                            ("personal", "Personal"),
                            ("professional", "Professional"),
                            ("open_source", "Open Source"),
                            ("freelance", "Freelance"),
                        ],
                        default="personal",
                        max_length=20,
                    ),
                ),
                ("github_repo", models.URLField(blank=True)),
                ("live_url", models.URLField(blank=True)),
                ("case_study_url", models.URLField(blank=True)),
                ("year", models.PositiveIntegerField()),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("is_from_github", models.BooleanField(default=False)),
                ("github_repo_id", models.PositiveIntegerField(blank=True, null=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "technologies",
                    models.ManyToManyField(
                        blank=True, related_name="projects", to="skills.skill"
                    ),
                ),
            ],
            options={
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
                "ordering": ["-is_featured", "-year", "order"],
            },
        ),
        migrations.CreateModel(
            name="ProjectFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=200)),
                ("description_en", models.CharField(blank=True, max_length=200)),
                ("description_fr", models.CharField(blank=True, max_length=200)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="features",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Feature",
                "verbose_name_plural": "Project Features",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ProjectImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="projects/gallery/")),
                ("caption", models.CharField(blank=True, max_length=200)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Image",
                "verbose_name_plural": "Project Images",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ProjectLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("demo", "Demo"),
                            ("code", "Code"),
                            ("docs", "Documentation"),
                            ("video", "Video"),
                            ("case_study", "Case Study"),
                        ],
                        max_length=20,
                    ),
                ),
                ("url", models.URLField()),
                ("icon_class", models.CharField(blank=True, max_length=50)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Link",
                "verbose_name_plural": "Project Links",
                "ordering": ["type"],
            },
        ),
    ]
